### ISSUE TITLE
Confirming ECDSA support for DTLS

### ISSUE THREAD

**Issue by ohmycaptainnemo** [boaks/zephyr-coaps-client#2]
@boaks 

Hi. Would really like to thank you for your fantastic work on CoAP, Eclipse Californium and this repo.
I noticed that in [dtls_credentials.c](https://github.com/boaks/zephyr-coaps-client/blob/main/src/dtls_credentials.c), there are keys defined for DTLS ECC, however I could not find any examples of them being used here. I also came across this support link that seems to suggest that the Nordic boards only support PSK for DTLS for CoAP:

[https://devzone.nordicsemi.com/f/nordic-q-a/89511/coap-with-dtls-on-download-sample](https://devzone.nordicsemi.com/f/nordic-q-a/89511/coap-with-dtls-on-download-sample)

I would like to clarify then why you have defined the keys here? Would I be able to program say a nrf9160 with CA cert, device cert and private key to use for DTLS with CoAP or is it still not supported to your knowledge?

Thanks.

**Comment by boaks** [comment]
> Would really like to thank you for your fantastic work 

You're welcome.

> however I could not find any examples of them being used here

The demo is using [Eclipse/tinydtls](https://github.com/eclipse/tinydtls) "offloaded from the modem and socket". 
Tinydtls comes with support for Raw Public Key ([RFC 7250](https://www.rfc-editor.org/info/rfc7250)) but not with support for x509.

To enable the use of ECDSA with RFC 7250, the tinydtls module offers a KConfig flag, see

KConfig: "Zephyr Kernel" > "Modules" > "tinydtls" > "tinyDTLS Settings" > "Enable libtinydtls" > "Enable ECDHE_ECDSA"

The current support is limited:
- it doesn't use the HW ecc accelerator, therefore the handshakes takes a couple of seconds (10-20s).
- `verify_ecdsa_key` is empty, means, all certificates are trusted, which is obviously not the "final intention".
- same applies to the Californium, where you need to add the devices public keys as trusted to the CertificateVerifier.

The reason not to do this so far is, that for me it's more important to have a e2e setup, means from the device to a SPA browser app to show the data.

>  I also came across this support link that seems to suggest that the Nordic boards only support PSK for DTLS for CoAP:

That's deprecated. In the meantime x509 is supported for DTLS by the nRF9160 modem firmware (1.3.5). You need to take care about the certificate size limit. However, my demo is a year older than the DTLS 1.2 CID support from Nordic (which is based on mbedtls) and therefore it's based on tinydtls in the application code and not on the modem's DTLS function.

**Comment by ohmycaptainnemo** [comment]
Amazing. Thank you.

**Comment by boaks** [comment]
Update:

In the meantime there is `micro-ecc` support for tinydtls (under development).
That's pretty fast (1-2s) and I use it since a year now for almost all devices.
 
See [tinydtls - PR 228](https://github.com/eclipse-tinydtls/tinydtls/pull/228) and [tinydtls - PR 229](https://github.com/eclipse-tinydtls/tinydtls/pull/229). 

Both are included in the used [boaks/tinydtls - zephyr_cid_develop](https://github.com/boaks/tinydtls/tree/zephyr_cid_develop) branch in my fork.
