### ISSUE TITLE
Is this compatible with nRF9151/nRF9161

### ISSUE THREAD

**Issue by rajeev1986** [boaks/zephyr-coaps-client#3]
@boaks, this is some good stuff. I am planning to test it out in the coming days. Do you think the current version is also compatible with nRF9151/nRF9161 just by adding these boards?
Thanks

**Comment by rajeev1986** [comment]
Sorry ignore my comment. I saw that in the readme nRF9161 is supported.

**Comment by boaks** [comment]
You're welcome.

I released currently the 0.10.0, and you may be the first to test it. 
I guess, we are linked in LinkedIn. If you stick at any point or have any questions, don't hesitate to ask on your preferred channel, here, linkedin or e-Mail.
